version: '2.1'
services:
  odoo:
    image: anybox/odoo-oca:10.0
    restart: unless-stopped
    volumes:
      - conf:/etc/odoo
      - data_dir:/var/lib/odoo
      - pgsocket:/var/run/postgresql
#    networks:
#      - caddy_default
    ports:
      - "8069"
      - "8072"
    command: /srv/odoo/odoo-bin -i disable_odoo_online,backend_theme_v10,res_config_settings_enterprise_remove

  postgresql:
    image: postgresql:odoo10
    restart: unless-stopped
    volumes:
      - pgsocket:/var/run/postgresql
      - postgres:/var/lib/postgresql/data

volumes:
  conf:
#    driver: anybox/buttervolume:latest
  data_dir:
#    driver: anybox/buttervolume:latest
  postgres:
#    driver: anybox/buttervolume:latest
  pgsocket:

#networks:
#  caddy_default:
#    external: true
