variables:
  IMAGE: "$CI_REGISTRY_IMAGE"
  COMMIT_TAG: "$CI_COMMIT_REF_NAME"
  COMPOSE_FILE_TESTS: docker-compose-tests.yml

services:
  - docker:dind

stages:
  - build1
  - build2
  # - optimization
  # - test
  - pre-deploy
  - deploy
  - post-deploy

build-base:
  stage: build1
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY
    - docker pull $IMAGE/postgresql:11 || true
    - docker pull $IMAGE/debian:stretch || true
    - docker build --cache-from $IMAGE/postgresql:11 -t $IMAGE/postgresql:11 postgresql
    - docker build --cache-from $IMAGE/debian:stretch -t $IMAGE/debian:stretch debian
    - docker push $IMAGE/postgresql:11
    - docker push $IMAGE/debian:stretch

build-oca:
  stage: build2
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY
    - docker pull $IMAGE/postgresql:11
    - docker pull $IMAGE/debian:stretch
    - docker pull $IMAGE/ocb:$COMMIT_TAG || true
    - docker pull $IMAGE/ocb-oca:$COMMIT_TAG || true
    - docker build --cache-from $IMAGE/ocb:$COMMIT_TAG -t $IMAGE/ocb:$COMMIT_TAG ocb
    - docker build --cache-from $IMAGE/ocb-oca:$COMMIT_TAG -t $IMAGE/ocb-oca:$COMMIT_TAG ocb-oca
    - docker push $IMAGE/ocb:$COMMIT_TAG
    - docker push $IMAGE/ocb-oca:$COMMIT_TAG

build-openupgrade:
  stage: build2
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY
    - docker pull $IMAGE/postgresql:11
    - docker pull $IMAGE/debian:stretch
    - docker pull $IMAGE/openupgrade:$COMMIT_TAG || true
    - docker pull $IMAGE/openupgrade-oca:$COMMIT_TAG || true
    - docker build --cache-from $IMAGE/openupgrade:$COMMIT_TAG -t $IMAGE/openupgrade:$COMMIT_TAG openupgrade
    - docker build --cache-from $IMAGE/openupgrade-oca:$COMMIT_TAG -t $IMAGE/openupgrade-oca:$COMMIT_TAG openupgrade-oca
    - docker push $IMAGE/openupgrade:$COMMIT_TAG
    - docker push $IMAGE/openupgrade-oca:$COMMIT_TAG

build-ee:
  stage: build2
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY
    - docker pull $IMAGE/postgresql:11
    - docker pull $IMAGE/debian:stretch
    - docker pull $IMAGE/odoo:$COMMIT_TAG || true
    - docker pull $IMAGE/odoo-ee:$COMMIT_TAG || true
    - docker build --cache-from $IMAGE/odoo:$COMMIT_TAG -t $IMAGE/odoo:$COMMIT_TAG odoo
    - docker build --cache-from $IMAGE/odoo-ee:$COMMIT_TAG -t $IMAGE/odoo-ee:$COMMIT_TAG --build-arg GITHUB_TOKEN=$GITHUB_TOKEN odoo-ee
    - docker push $IMAGE/odoo:$COMMIT_TAG
    - docker push $IMAGE/odoo-ee:$COMMIT_TAG

test:
  stage: test
  image: registry.anybox.cloud/infra/infra-cli:dev
  script:
    - export DOCKER_HOST=tcp://docker:2375/
    - make test
    - toolbox_cli analyse-odoo-tests test.log
  artifacts:
    when: always
    paths:
      - test.log
    expire_in: 1 day


# container_scanning:
#   stage: optimization
#   variables:
#     DOCKER_DRIVER: overlay2
#   services:
#     - docker:stable-dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_ENV_CI_REGISTRY
#     - docker run -d --name db arminc/clair-db:latest
#     - docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
#     - apk add -U wget ca-certificates
#     - docker pull $CI_REGISTRY_IMAGE:$COMMIT_TAG
#     - wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
#     - mv clair-scanner_linux_amd64 clair-scanner
#     - chmod +x clair-scanner
#     - touch clair-whitelist.yml
#     - while( ! wget -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; done
#     - retries=0
#     - echo "Waiting for clair daemon to start"
#     - while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
#     - ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml $CI_REGISTRY_IMAGE:$COMMIT_TAG || true
#   allow_failure: true
#   artifacts:
#     paths:
#       - gl-container-scanning-report.json
