version: '3.7'

services:
  odoo:
    image: registry.anybox.cloud/anybox/odoo-docker/ocb-oca:12.0
    build: .
    depends_on:
      - db
    volumes:
      - odoodata:/var/lib/odoo
      - pgsocket:/var/run/postgresql
    ports:
      - "8069:8069"
      - "8072:8072"
    command: /srv/odoo/openerp-server -i base,disable_odoo_online,backend_theme_v12,res_config_settings_enterprise_remove,website_odoo_debranding

  db:
    build: ../postgresql
    volumes:
      - pgsocket:/var/run/postgresql
      - pgdata:/var/lib/postgresql/data
volumes:
  odoodata:
  pgdata:
  pgsocket:
