version: '3.7'

services:
  odoo:
    build: .
    depends_on:
      - db
    volumes:
      - odoodata:/var/lib/odoo
      - pgsocket:/var/run/postgresql
    ports:
      - "8069:8069"
      - "8072:8072"
    command: /srv/odoo/odoo.py -c /etc/odoo.odoo.conf -i base

  db:
    build: ../postgresql
    volumes:
      - pgsocket:/var/run/postgresql
      - pgdata:/var/lib/postgresql/data
volumes:
  odoodata:
  pgdata:
  pgsocket:
