version: '3.7'

services:
  odoo:
    image: registry.anybox.cloud/anybox/odoo-docker/odoo:13.0
    build:
        context: .
        args:
            GHUSER: OCA
            GHREPO: OCB
    depends_on:
      - db
    volumes:
      - odoodata:/var/lib/odoo
      - pgsocket:/var/run/postgresql
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      WAIT_FOR_LOCAL_DB: "true"
    command: /srv/odoo/odoo-bin -i base

  db:
    build: ../postgresql
    volumes:
      - pgsocket:/var/run/postgresql
      - pgdata:/var/lib/postgresql/data
volumes:
  odoodata:
  pgdata:
  pgsocket:
